name: CI/CD for VisionF1 Predictions API Deployment to Heroku

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lints the code
    runs-on: ubuntu-latest

    steps:
      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove development-only files
        run: |
          rm -f .env
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh 
      - uses: akhileshns/heroku-deploy@v3.14.15 # This is the action for deploying to Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "visionf1-predictions"
          heroku_email: "afabregas@fi.uba.ar"